{"name": "test_post_comment_by_id[invalid_id]", "status": "skipped", "statusDetails": {"message": "XFAIL Id isn't exists\n\nAssertionError: Wrong response code. (403)", "trace": "self = <tests.test_comments.TestComments object at 0x03A533A0>\napi = <utils.request_helper.ApiSession object at 0x03A613A0>\nthread_id = 't3_yyyyyyy'\n\n    @pytest.mark.run(order=-3)\n    @allure.story('Тест: Оставить комментарий')\n    @pytest.mark.parametrize('thread_id', [pytest.param('t3_f3dfc6', marks=pytest.mark.positive),\n                                           pytest.param(MANUALLY_POSTED_COMMENT_ID, marks=pytest.mark.positive),\n                                           pytest.param('t3_yyyyyyy', marks=(pytest.mark.xfail(reason=\"Id isn't exists\"), pytest.mark.negative))],\n                             ids=['comment_a_post', 'reply_on_a_comment', 'invalid_id'])\n    def test_post_comment_by_id(self, api, thread_id):\n        \"\"\"POST to comment a thread by id\"\"\"\n    \n        comment_text = \"hello there\"\n        data = {\n            'api_type': 'json',\n            'return_rtjson': False,\n            'text': comment_text,\n            'thing_id': thread_id\n        }\n        response = api.post(path=self.COMMENT_PATH, data=data)\n    \n>       assert_code(response, 200)\n\ntests\\test_comments.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [403]>, expected_code = 200\n\n    @allure.step('Проверка: код ответа совпадает с ожидаемым.')\n    def assert_code(response, expected_code: int):\n>       assert response.status_code == expected_code, f'Wrong response code. ({response.status_code})'\nE       AssertionError: Wrong response code. (403)\n\nutils\\assertions.py:12: AssertionError"}, "description": "POST to comment a thread by id", "steps": [{"name": "POST request to: https://oauth.reddit.com/api/comment", "status": "passed", "start": 1657544398598, "stop": 1657544398863}, {"name": "Проверка: код ответа совпадает с ожидаемым.", "status": "failed", "statusDetails": {"message": "AssertionError: Wrong response code. (403)\n", "trace": "  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\RedditAPI\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\RedditAPI\\utils\\assertions.py\", line 12, in assert_code\n    assert response.status_code == expected_code, f'Wrong response code. ({response.status_code})'\n"}, "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "expected_code", "value": "200"}], "start": 1657544398863, "stop": 1657544398863}], "parameters": [{"name": "thread_id", "value": "'t3_yyyyyyy'"}], "start": 1657544398598, "stop": 1657544398863, "uuid": "fb1a86ca-5f51-41b0-9b99-870d3a19ba68", "historyId": "e342a320e2588d65600bc3a2d7b385cb", "testCaseId": "eec84c0df8c4802f5a71678d9cdea901", "fullName": "tests.test_comments.TestComments#test_post_comment_by_id", "labels": [{"name": "feature", "value": "Тесты работы с комментариями"}, {"name": "story", "value": "Тест: Оставить комментарий"}, {"name": "tag", "value": "run(order=-3)"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Id isn't exists')"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_comments"}, {"name": "subSuite", "value": "TestComments"}, {"name": "host", "value": "ArtemKozlov"}, {"name": "thread", "value": "6644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_comments"}]}